
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.2'
version_full = '9b9cea24d00b8b019e943a3cd67c58868ffd7bb0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

