
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4'
version_full = 'd80fdaa4c6d4f914c6b5d85467afe3811881ea14'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

