
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e3acfe80c184a1f192bcce5f92ed5b0efde454f3",
 "version": "0.3.post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
