
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.4'
version_full = '3fabc788c27b2c2619d8e23b3eebc018b95faf7a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

