
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b74bea67a5c04d6062e4f54dc26739d1457f0241",
 "version": "1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
