
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b493739a78e3ac471fe10c4e55816111b8507c2d",
 "version": "0.3.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
