
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = '069ef4ccc44eb5912c7c52a823f2d1b33a9924fd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

