# the root path your site will be served. e.g. "/mysite", (default: "", no sub_path)
root = ""

[blog]
short_name = "编程小梦" #在导航栏显示
long_name = "编程小梦--康凯森的技术博客" #作为网页的 title 显示
theme = "theme"  # path to theme

[author]
name = "康凯森"

[theme]
github = "kangkaisen"
