"""
   CorasLib.Models.AllocationItemSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper

class AllocationItemSerializer(object):

    """Implementation of the 'AllocationItemSerializer' model.

    TODO: type model description here.

    Attributes:
        first_seat (string): TODO: type description here.
        price (int): TODO: type description here.
        section (string): TODO: type description here.
        block (string): TODO: type description here.
        mtype (int): TODO: type description here.
        last_seat (string): TODO: type description here.
        row (string): TODO: type description here.
        count (int): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the AllocationItemSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    first_seat -- string -- Sets the attribute first_seat
                    price -- int -- Sets the attribute price
                    section -- string -- Sets the attribute section
                    block -- string -- Sets the attribute block
                    type -- int -- Sets the attribute mtype
                    last_seat -- string -- Sets the attribute last_seat
                    row -- string -- Sets the attribute row
                    count -- int -- Sets the attribute count
        
        """
        # Set all of the parameters to their default values
        self.first_seat = None
        self.price = None
        self.section = None
        self.block = None
        self.mtype = None
        self.last_seat = None
        self.row = None
        self.count = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "first_seat": "first_seat",
            "price": "price",
            "section": "section",
            "block": "block",
            "type": "mtype",
            "last_seat": "last_seat",
            "row": "row",
            "count": "count",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "first_seat": "first_seat",
            "price": "price",
            "section": "section",
            "block": "block",
            "mtype": "type",
            "last_seat": "last_seat",
            "row": "row",
            "count": "count",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)