"""
   CorasLib.Models.SectionSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper

class SectionSerializer(object):

    """Implementation of the 'SectionSerializer' model.

    TODO: type model description here.

    Attributes:
        url (string): TODO: type description here.
        date_created (DateTime): TODO: type description here.
        configuration (string): TODO: type description here.
        id (string): TODO: type description here.
        date_modified (DateTime): TODO: type description here.
        name (string): TODO: type description here.
        is_ga (bool): TODO: type description here.
        capacity (int): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the SectionSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    url -- string -- Sets the attribute url
                    date_created -- DateTime -- Sets the attribute date_created
                    configuration -- string -- Sets the attribute configuration
                    id -- string -- Sets the attribute id
                    date_modified -- DateTime -- Sets the attribute date_modified
                    name -- string -- Sets the attribute name
                    is_ga -- bool -- Sets the attribute is_ga
                    capacity -- int -- Sets the attribute capacity
        
        """
        # Set all of the parameters to their default values
        self.url = None
        self.date_created = None
        self.configuration = None
        self.id = None
        self.date_modified = None
        self.name = None
        self.is_ga = None
        self.capacity = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "url": "url",
            "date_created": "date_created",
            "configuration": "configuration",
            "id": "id",
            "date_modified": "date_modified",
            "name": "name",
            "is_ga": "is_ga",
            "capacity": "capacity",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "url": "url",
            "date_created": "date_created",
            "configuration": "configuration",
            "id": "id",
            "date_modified": "date_modified",
            "name": "name",
            "is_ga": "is_ga",
            "capacity": "capacity",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)