"""
   CorasLib.Models.WritePriceChartSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper
from CorasLib.Models.PriceSerializer import PriceSerializer

class WritePriceChartSerializer(object):

    """Implementation of the 'WritePriceChartSerializer' model.

    TODO: type model description here.

    Attributes:
        name (string): TODO: type description here.
        currency (string): TODO: type description here.
        prices (list of PriceSerializer): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WritePriceChartSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    name -- string -- Sets the attribute name
                    currency -- string -- Sets the attribute currency
                    prices -- list of PriceSerializer -- Sets the attribute prices
        
        """
        # Set all of the parameters to their default values
        self.name = None
        self.currency = None
        self.prices = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "name": "name",
            "currency": "currency",
            "prices": "prices",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "prices" in kwargs:
                # Parameter is an array, so we need to iterate through it
                self.prices = list()
                for item in kwargs["prices"]:
                    self.prices.append(PriceSerializer(**item))

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "name": "name",
            "currency": "currency",
            "prices": "prices",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)