
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.70'
version_full = '26df0cb45db3ea05441ee6d3035e1898deed6c58'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

