
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a17'
version_full = '59c6d4f242f8dad771ecc55021771e8482d58b91'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

