
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d11885a7079da575f4ecb297d8eb88f5390fec1e",
 "version": "0.2.post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
