language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - pip install codecov
install:
    - pip install .
script: 
    - coverage run -p tests/all_tests.py
after_success:
    - coverage combine
    - codecov