
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ccef1eb9babf2443a77d68ce2a26fb6e00cc85c4",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
