language: python
sudo: false
python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5

env:
 - DJANGO_VERSION=1.5.12
 - DJANGO_VERSION=1.6.11
 - DJANGO_VERSION=1.7.10
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.9b1

install:
  - travis_retry pip install -q mock==1.0.1 Django==$DJANGO_VERSION coverage coveralls

script:
  - coverage run --source=guardian setup.py test

after_success:
  - coverage report --omit "guardian/compat.py,guardian/testsettings.py" -m guardian/*.py
  - coveralls

notifications:
  irc: "irc.freenode.net#django-guardian"


matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.9b1
        - python: 3.5
          env: DJANGO_VERSION=1.5.12
        - python: 3.5
          env: DJANGO_VERSION=1.6.11
        - python: 3.5
          env: DJANGO_VERSION=1.7.10
