
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "89a8e9af4ada133a77e22a75f7dfd2bf6f4b83d9",
 "version": "2.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
