
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "40e82628715d18afc31361ab721090697aa22f46",
 "version": "1.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
