
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.69'
version_full = 'f7c97c38d4cdbed84660a03f8dd9659b91780a46'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

