language: python
python:
  - "2.7"

before_install:
  - wget https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
  - tar xzf v0.4.0.tar.gz
  - export PATH=$PWD/bats-0.4.0/bin:$PATH
  - bats -v

install:
  - virtualenv .venv
  - . ./.venv/bin/activate
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install -e .

script:
  - export PATH=$PWD/bats-0.4.0/bin:$PATH
  - tests/run_tests.sh

sudo: false
