# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2015-11-24 10:53:27.960396
from __future__ import unicode_literals
import datetime

version = "1.1rc1"
githash = "1ac98cd9682acc96fbb03bcda2d47cd720de3ce7"


major = 1
minor = 1
bugfix = 0

release = True
timestamp = datetime.datetime(2015, 11, 24, 10, 53, 27, 960396)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
