image: hobarrera/python:latest

before_script:
  - pip install tox setuptools

py33:
  stage: test
  script:
    - tox -e py33

py34:
  stage: test
  script:
    - tox -e py34

py35:
  stage: test
  script:
    - tox -e py35

style:
  stage: test
  script:
    - tox -e style
