
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ab686739c217dab161248ff3b24d863ceb71468f",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
