
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.4'
version_full = '1b7966fb1ddad1e848888e61aefe1239944acd01'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

