
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "914f24efb5503b3f6adf2b5b09b5c1bb74f416aa",
 "version": "0.3.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
