
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "66a8a1cabc06f0ce288bf2372e5a7e29c9ae9fbb",
 "version": "0.1.post18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
