
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3d1aa39be5694945d7a52e8042f288901f3081a9",
 "version": "2.9.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
