
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "669bd187d4802863cf7f8cc56cae1963c6fb3969",
 "version": "v0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
