
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bfd1aaf8dde4dc0fdead412c57003e01ec4a7477",
 "version": "0.3.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
