# base_url: http://misaka.61924.nl
base_url: http://0.0.0.0:8080

links:
 - ['', 'index']
 - ['changelog', 'changelog']
 - ['manual', 'manual']
 - ['api', 'api']
 - ['development', 'development']

root:
 - index
 - '404'

post_scripts:
 - process_assets.sh

misaka_extensions:
 - no_intra_emphasis
 - tables
 - fenced_code
 - autolink
 - strikethrough
 - superscript

# Javascript dependencies:
#
# - LESS
