#!/usr/bin/env python

class Calendar(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Name': 'str',
            'Uid': 'int',
            'Days': 'list[WeekDay]',
            'Exceptions': 'list[CalendarException]',
            'IsBaseCalendar': 'bool',
            'IsBaselineCalendar': 'bool'

        }

        self.attributeMap = {
            'Name': 'Name','Uid': 'Uid','Days': 'Days','Exceptions': 'Exceptions','IsBaseCalendar': 'IsBaseCalendar','IsBaselineCalendar': 'IsBaselineCalendar'}       

        self.Name = None # str
        self.Uid = None # int
        self.Days = None # list[WeekDay]
        self.Exceptions = None # list[CalendarException]
        self.IsBaseCalendar = None # bool
        self.IsBaselineCalendar = None # bool
        
