#!/usr/bin/env python

class CalendarItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Link': 'Link',
            'Uid': 'int',
            'Name': 'str'

        }

        self.attributeMap = {
            'Link': 'Link','Uid': 'Uid','Name': 'Name'}       

        self.Link = None # Link
        self.Uid = None # int
        self.Name = None # str
        
