#!/usr/bin/env python

class ExtendedAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'FieldId': 'str',
            'Value': 'str',
            'ValueGuid': 'str',
            'DurationFormat': 'TimeUnitType'

        }

        self.attributeMap = {
            'FieldId': 'FieldId','Value': 'Value','ValueGuid': 'ValueGuid','DurationFormat': 'DurationFormat'}       

        self.FieldId = None # str
        self.Value = None # str
        self.ValueGuid = None # str
        self.DurationFormat = None # TimeUnitType
        
