#!/usr/bin/env python

class OutlineMask(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Level': 'int',
            'Type': 'MaskType',
            'Length': 'int',
            'Separator': 'str'

        }

        self.attributeMap = {
            'Level': 'Level','Type': 'Type','Length': 'Length','Separator': 'Separator'}       

        self.Level = None # int
        self.Type = None # MaskType
        self.Length = None # int
        self.Separator = None # str
        
