#!/usr/bin/env python

class OutlineCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'FieldId': 'str',
            'ValueId': 'int',
            'ValueGuid': 'str'

        }

        self.attributeMap = {
            'FieldId': 'FieldId','ValueId': 'ValueId','ValueGuid': 'ValueGuid'}       

        self.FieldId = None # str
        self.ValueId = None # int
        self.ValueGuid = None # str
        
