#!/usr/bin/env python

class OutlineCodeDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Guid': 'str',
            'FieldId': 'str',
            'FieldName': 'str',
            'Alias': 'str',
            'PhoneticAlias': 'str',
            'Values': 'list[OutlineValue]',
            'Enterprise': 'bool',
            'EnterpriseOutlineCodeAlias': 'int',
            'ResourceSubstitutionEnabled': 'bool',
            'LeafOnly': 'bool',
            'AllLevelsRequired': 'bool',
            'OnlyTableValuesAllowed': 'bool',
            'Masks': 'list[OutlineMask]',
            'ShowIndent': 'bool'

        }

        self.attributeMap = {
            'Guid': 'Guid','FieldId': 'FieldId','FieldName': 'FieldName','Alias': 'Alias','PhoneticAlias': 'PhoneticAlias','Values': 'Values','Enterprise': 'Enterprise','EnterpriseOutlineCodeAlias': 'EnterpriseOutlineCodeAlias','ResourceSubstitutionEnabled': 'ResourceSubstitutionEnabled','LeafOnly': 'LeafOnly','AllLevelsRequired': 'AllLevelsRequired','OnlyTableValuesAllowed': 'OnlyTableValuesAllowed','Masks': 'Masks','ShowIndent': 'ShowIndent'}       

        self.Guid = None # str
        self.FieldId = None # str
        self.FieldName = None # str
        self.Alias = None # str
        self.PhoneticAlias = None # str
        self.Values = None # list[OutlineValue]
        self.Enterprise = None # bool
        self.EnterpriseOutlineCodeAlias = None # int
        self.ResourceSubstitutionEnabled = None # bool
        self.LeafOnly = None # bool
        self.AllLevelsRequired = None # bool
        self.OnlyTableValuesAllowed = None # bool
        self.Masks = None # list[OutlineMask]
        self.ShowIndent = None # bool
        
