#!/usr/bin/env python

class RecurringInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'RecurrencePattern': 'RecurrencePattern',
            'StartDate': 'DateTime',
            'EndDate': 'DateTime',
            'Duration': 'str',
            'DurationString': 'str',
            'Occurrences': 'int',
            'UseEndDate': 'bool',
            'DailyRepetitions': 'int',
            'DailyUseWorkdays': 'bool',
            'WeeklyRepetitions': 'int',
            'WeeklyDays': 'WeekDayType',
            'MonthlyUseOrdinalDay': 'bool',
            'MonthlyOrdinalNumber': 'OrdinalNumber',
            'MonthlyOrdinalDay': 'str',
            'MonthlyOrdinalRepetitions': 'int',
            'MonthlyDay': 'int',
            'MonthlyRepetitions': 'int',
            'YearlyUseOrdinalDay': 'bool',
            'YearlyDate': 'DateTime',
            'YearlyOrdinalNumber': 'OrdinalNumber',
            'YearlyOrdinalDay': 'str',
            'YearlyOrdinalMonth': 'Month'

        }

        self.attributeMap = {
            'RecurrencePattern': 'RecurrencePattern','StartDate': 'StartDate','EndDate': 'EndDate','Duration': 'Duration','DurationString': 'DurationString','Occurrences': 'Occurrences','UseEndDate': 'UseEndDate','DailyRepetitions': 'DailyRepetitions','DailyUseWorkdays': 'DailyUseWorkdays','WeeklyRepetitions': 'WeeklyRepetitions','WeeklyDays': 'WeeklyDays','MonthlyUseOrdinalDay': 'MonthlyUseOrdinalDay','MonthlyOrdinalNumber': 'MonthlyOrdinalNumber','MonthlyOrdinalDay': 'MonthlyOrdinalDay','MonthlyOrdinalRepetitions': 'MonthlyOrdinalRepetitions','MonthlyDay': 'MonthlyDay','MonthlyRepetitions': 'MonthlyRepetitions','YearlyUseOrdinalDay': 'YearlyUseOrdinalDay','YearlyDate': 'YearlyDate','YearlyOrdinalNumber': 'YearlyOrdinalNumber','YearlyOrdinalDay': 'YearlyOrdinalDay','YearlyOrdinalMonth': 'YearlyOrdinalMonth'}       

        self.RecurrencePattern = None # RecurrencePattern
        self.StartDate = None # DateTime
        self.EndDate = None # DateTime
        self.Duration = None # str
        self.DurationString = None # str
        self.Occurrences = None # int
        self.UseEndDate = None # bool
        self.DailyRepetitions = None # int
        self.DailyUseWorkdays = None # bool
        self.WeeklyRepetitions = None # int
        self.WeeklyDays = None # WeekDayType
        self.MonthlyUseOrdinalDay = None # bool
        self.MonthlyOrdinalNumber = None # OrdinalNumber
        self.MonthlyOrdinalDay = None # str
        self.MonthlyOrdinalRepetitions = None # int
        self.MonthlyDay = None # int
        self.MonthlyRepetitions = None # int
        self.YearlyUseOrdinalDay = None # bool
        self.YearlyDate = None # DateTime
        self.YearlyOrdinalNumber = None # OrdinalNumber
        self.YearlyOrdinalDay = None # str
        self.YearlyOrdinalMonth = None # Month
        
