#!/usr/bin/env python

class TaskItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Link': 'Link',
            'Uid': 'int',
            'Id': 'int',
            'Name': 'str',
            'Start': 'DateTime',
            'Finish': 'DateTime',
            'Duration': 'str',
            'DurationString': 'str'

        }

        self.attributeMap = {
            'Link': 'Link','Uid': 'Uid','Id': 'Id','Name': 'Name','Start': 'Start','Finish': 'Finish','Duration': 'Duration','DurationString': 'DurationString'}       

        self.Link = None # Link
        self.Uid = None # int
        self.Id = None # int
        self.Name = None # str
        self.Start = None # DateTime
        self.Finish = None # DateTime
        self.Duration = None # str
        self.DurationString = None # str
        
