#!/usr/bin/env python

class Value(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Id': 'int',
            'Val': 'str',
            'Description': 'str',
            'Phonetic': 'str'

        }

        self.attributeMap = {
            'Id': 'Id','Val': 'Val','Description': 'Description','Phonetic': 'Phonetic'}       

        self.Id = None # int
        self.Val = None # str
        self.Description = None # str
        self.Phonetic = None # str
        
