#!/usr/bin/env python

class WBSDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'CodePrefix': 'str',
            'GenerateWBSCode': 'bool',
            'VerifyUniqueness': 'bool',
            'CodeMaskCollection': 'list[WBSCodeMask]'

        }

        self.attributeMap = {
            'CodePrefix': 'CodePrefix','GenerateWBSCode': 'GenerateWBSCode','VerifyUniqueness': 'VerifyUniqueness','CodeMaskCollection': 'CodeMaskCollection'}       

        self.CodePrefix = None # str
        self.GenerateWBSCode = None # bool
        self.VerifyUniqueness = None # bool
        self.CodeMaskCollection = None # list[WBSCodeMask]
        
