# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/kRPCTest/Schema/Test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test/kRPCTest/Schema/Test.proto',
  package='Test',
  serialized_pb=_b('\n\x1ftest/kRPCTest/Schema/Test.proto\x12\x04Test*\x1f\n\x08TestEnum\x12\x05\n\x01\x61\x10\x01\x12\x05\n\x01\x62\x10\x02\x12\x05\n\x01\x63\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TESTENUM = _descriptor.EnumDescriptor(
  name='TestEnum',
  full_name='Test.TestEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='a', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='b', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='c', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=41,
  serialized_end=72,
)
_sym_db.RegisterEnumDescriptor(_TESTENUM)

TestEnum = enum_type_wrapper.EnumTypeWrapper(_TESTENUM)
a = 1
b = 2
c = 3


DESCRIPTOR.enum_types_by_name['TestEnum'] = _TESTENUM


# @@protoc_insertion_point(module_scope)
