
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.6'
version_full = 'c8fccffb9c832cf3e06d574b16ca110f2c2aa1de'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

