
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4450a10c885b294c95b3331db847aa27a276199b",
 "version": "2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
