
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "655f2b7dfd03b546c607486a15968e3b81af5edc",
 "version": "0.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
