
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a1'
version_full = 'da75f85c3e0827dac2e76720b3e57127de708113'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

