
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b814cfb903e1885f95be0ab9292ffdb4b77f360",
 "version": "0.2.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
