#!/usr/bin/env python

class ImagingResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Height': 'int',
            'Width': 'int',
            'BitsPerPixel': 'int',
            'BmpProperties': 'BmpProperties',
            'GifProperties': 'GifProperties',
            'JpegProperties': 'JpegProperties',
            'PngProperties': 'PngProperties',
            'TiffProperties': 'TiffProperties',
            'PsdProperties': 'PsdProperties',
            'HorizontalResolution': 'float',
            'VerticalResolution': 'float',
            'IsCached': 'bool',
            'Code': 'str',
            'Status': 'str'

        }

        self.attributeMap = {
            'Height': 'Height','Width': 'Width','BitsPerPixel': 'BitsPerPixel','BmpProperties': 'BmpProperties','GifProperties': 'GifProperties','JpegProperties': 'JpegProperties','PngProperties': 'PngProperties','TiffProperties': 'TiffProperties','PsdProperties': 'PsdProperties','HorizontalResolution': 'HorizontalResolution','VerticalResolution': 'VerticalResolution','IsCached': 'IsCached','Code': 'Code','Status': 'Status'}       

        self.Height = None # int
        self.Width = None # int
        self.BitsPerPixel = None # int
        self.BmpProperties = None # BmpProperties
        self.GifProperties = None # GifProperties
        self.JpegProperties = None # JpegProperties
        self.PngProperties = None # PngProperties
        self.TiffProperties = None # TiffProperties
        self.PsdProperties = None # PsdProperties
        self.HorizontalResolution = None # float
        self.VerticalResolution = None # float
        self.IsCached = None # bool
        self.Code = None # str
        self.Status = None # str
        
