#!/usr/bin/env python

class JfifData(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'DensityUnits': 'str',
            'Version': 'int',
            'XDensity': 'int',
            'YDensity': 'int'

        }

        self.attributeMap = {
            'DensityUnits': 'DensityUnits','Version': 'Version','XDensity': 'XDensity','YDensity': 'YDensity'}       

        self.DensityUnits = None # str
        self.Version = None # int
        self.XDensity = None # int
        self.YDensity = None # int
        
