#!/usr/bin/env python

class JpegProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Comment': 'str',
            'JpegExifData': 'JpegExifData',
            'JpegJfifData': 'JfifData'

        }

        self.attributeMap = {
            'Comment': 'Comment','JpegExifData': 'JpegExifData','JpegJfifData': 'JpegJfifData'}       

        self.Comment = None # str
        self.JpegExifData = None # JpegExifData
        self.JpegJfifData = None # JfifData
        
