# This file was auto-generated by salt's setup on Friday, 13 November 2015 @ 17:11:20 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 7, 0, 0, 0, None)
