# Autogenerated by Astropy's setup.py on 2015-10-05 17:51:29.297000
from __future__ import unicode_literals
import datetime

version = "1.0.5"
githash = "77280d6f110d1de6f0870fce1afb8d1b608bd7a7"


major = 1
minor = 0
bugfix = 5

release = True
timestamp = datetime.datetime(2015, 10, 5, 17, 51, 29, 297000)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
