# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pylogilcd', [dirname(__file__)])
        except ImportError:
            import _pylogilcd
            return _pylogilcd
        if fp is not None:
            try:
                _mod = imp.load_module('_pylogilcd', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pylogilcd = swig_import_helper()
    del swig_import_helper
else:
    import _pylogilcd
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pylogilcd.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pylogilcd.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pylogilcd.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pylogilcd.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pylogilcd.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pylogilcd.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pylogilcd.SwigPyIterator_copy(self)

    def next(self):
        return _pylogilcd.SwigPyIterator_next(self)

    def __next__(self):
        return _pylogilcd.SwigPyIterator___next__(self)

    def previous(self):
        return _pylogilcd.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pylogilcd.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pylogilcd.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pylogilcd.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pylogilcd.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pylogilcd.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pylogilcd.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pylogilcd.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pylogilcd.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pylogilcd.VectorInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pylogilcd.VectorInt___nonzero__(self)

    def __bool__(self):
        return _pylogilcd.VectorInt___bool__(self)

    def __len__(self):
        return _pylogilcd.VectorInt___len__(self)

    def pop(self):
        return _pylogilcd.VectorInt_pop(self)

    def __getslice__(self, i, j):
        return _pylogilcd.VectorInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pylogilcd.VectorInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pylogilcd.VectorInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pylogilcd.VectorInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pylogilcd.VectorInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pylogilcd.VectorInt___setitem__(self, *args)

    def append(self, x):
        return _pylogilcd.VectorInt_append(self, x)

    def empty(self):
        return _pylogilcd.VectorInt_empty(self)

    def size(self):
        return _pylogilcd.VectorInt_size(self)

    def clear(self):
        return _pylogilcd.VectorInt_clear(self)

    def swap(self, v):
        return _pylogilcd.VectorInt_swap(self, v)

    def get_allocator(self):
        return _pylogilcd.VectorInt_get_allocator(self)

    def begin(self):
        return _pylogilcd.VectorInt_begin(self)

    def end(self):
        return _pylogilcd.VectorInt_end(self)

    def rbegin(self):
        return _pylogilcd.VectorInt_rbegin(self)

    def rend(self):
        return _pylogilcd.VectorInt_rend(self)

    def pop_back(self):
        return _pylogilcd.VectorInt_pop_back(self)

    def erase(self, *args):
        return _pylogilcd.VectorInt_erase(self, *args)

    def __init__(self, *args):
        this = _pylogilcd.new_VectorInt(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _pylogilcd.VectorInt_push_back(self, x)

    def front(self):
        return _pylogilcd.VectorInt_front(self)

    def back(self):
        return _pylogilcd.VectorInt_back(self)

    def assign(self, n, x):
        return _pylogilcd.VectorInt_assign(self, n, x)

    def resize(self, *args):
        return _pylogilcd.VectorInt_resize(self, *args)

    def insert(self, *args):
        return _pylogilcd.VectorInt_insert(self, *args)

    def reserve(self, n):
        return _pylogilcd.VectorInt_reserve(self, n)

    def capacity(self):
        return _pylogilcd.VectorInt_capacity(self)
    __swig_destroy__ = _pylogilcd.delete_VectorInt
    __del__ = lambda self: None
VectorInt_swigregister = _pylogilcd.VectorInt_swigregister
VectorInt_swigregister(VectorInt)

class surface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, surface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, surface, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pylogilcd.new_surface(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def blitz(self, surface_, x=0, y=0, overwrite=True):
        return _pylogilcd.surface_blitz(self, surface_, x, y, overwrite)

    def invert(self):
        return _pylogilcd.surface_invert(self)

    def split(self, *args):
        return _pylogilcd.surface_split(self, *args)

    def getpixel(self, x, y):
        return _pylogilcd.surface_getpixel(self, x, y)

    def setpixel(self, x, y, val):
        return _pylogilcd.surface_setpixel(self, x, y, val)

    def getwidth(self):
        return _pylogilcd.surface_getwidth(self)

    def getheight(self):
        return _pylogilcd.surface_getheight(self)
    __swig_destroy__ = _pylogilcd.delete_surface
    __del__ = lambda self: None
surface_swigregister = _pylogilcd.surface_swigregister
surface_swigregister(surface)
cvar = _pylogilcd.cvar
LCD_WIDTH = cvar.LCD_WIDTH
LCD_HEIGHT = cvar.LCD_HEIGHT

class bitmapfont(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bitmapfont, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bitmapfont, name)
    __repr__ = _swig_repr

    def __init__(self, fname, charw, charh, charpr, charrefs):
        this = _pylogilcd.new_bitmapfont(fname, charw, charh, charpr, charrefs)
        try:
            self.this.append(this)
        except:
            self.this = this

    def getcharsurface(self, ichar):
        return _pylogilcd.bitmapfont_getcharsurface(self, ichar)

    def getstringsurface(self, string_):
        return _pylogilcd.bitmapfont_getstringsurface(self, string_)
    __swig_destroy__ = _pylogilcd.delete_bitmapfont
    __del__ = lambda self: None
bitmapfont_swigregister = _pylogilcd.bitmapfont_swigregister
bitmapfont_swigregister(bitmapfont)

class app(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, app, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, app, name)
    __repr__ = _swig_repr

    def __init__(self, Appname):
        this = _pylogilcd.new_app(Appname)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pylogilcd.delete_app
    __del__ = lambda self: None

    def update(self, *args):
        return _pylogilcd.app_update(self, *args)

    def getbuttonpressed(self, button):
        return _pylogilcd.app_getbuttonpressed(self, button)
app_swigregister = _pylogilcd.app_swigregister
app_swigregister(app)

# This file is compatible with both classic and new-style classes.


