
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2'
version_full = '208871db96689c911e00b9d59dace2de68df3220'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

