"""
   CorasLib.Models.WriteAddressSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper

class WriteAddressSerializer(object):

    """Implementation of the 'WriteAddressSerializer' model.

    TODO: type model description here.

    Attributes:
        city (string): TODO: type description here.
        address_2 (string): TODO: type description here.
        address_1 (string): TODO: type description here.
        postcode (string): TODO: type description here.
        address_3 (string): TODO: type description here.
        state (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WriteAddressSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    city -- string -- Sets the attribute city
                    address2 -- string -- Sets the attribute address_2
                    address1 -- string -- Sets the attribute address_1
                    postcode -- string -- Sets the attribute postcode
                    address3 -- string -- Sets the attribute address_3
                    state -- string -- Sets the attribute state
        
        """
        # Set all of the parameters to their default values
        self.city = None
        self.address_2 = None
        self.address_1 = None
        self.postcode = None
        self.address_3 = None
        self.state = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "city": "city",
            "address2": "address_2",
            "address1": "address_1",
            "postcode": "postcode",
            "address3": "address_3",
            "state": "state",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "city": "city",
            "address_2": "address2",
            "address_1": "address1",
            "postcode": "postcode",
            "address_3": "address3",
            "state": "state",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)