# Autogenerated by Astropy's setup.py on 2015-12-07 18:19:00.252049
from __future__ import unicode_literals
import datetime

version = "1.1rc2"
githash = "94d462ab82db1f65b4ffeda77ca76cae3f234862"


major = 1
minor = 1
bugfix = 0

release = True
timestamp = datetime.datetime(2015, 12, 7, 18, 19, 0, 252049)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
