language: python
os: linux
python: "2.7"

sudo: false

addons:
  apt:
    source:
      - lucid
    packages:
      - python-opencv

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install python-opencv
#   - sudo dpkg -L python-opencv

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
      export py=$PYTHON_VERSION;
    else
      export OS="Linux";
      export py=$TRAVIS_PYTHON_VERSION;
    fi
  - if [[ "${py:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - |
      if [[ "${py:0:1}" == '3' ]]; then
        NUMPY_VERSION=1.9.2
        SCIPY_VERSION=0.16.0
        MPL_VERSION=1.4.3
        BASEMAP_VERSION=1.0.7
      else
        NUMPY_VERSION=1.8.2
        SCIPY_VERSION=0.14.0
        MPL_VERSION=1.3.1
        BASEMAP_VERSION=1.0.7
      fi
  - conda create -q -n test-environment
        python=$py
        numpy=$NUMPY_VERSION
        scipy=$SCIPY_VERSION
        matplotlib=$MPL_VERSION
        basemap=$BASEMAP_VERSION
        flake8
        future
        lxml
        sqlalchemy
        mock
        nose
        gdal
        pyproj
        docopt
        coverage
        requests
  - source activate test-environment
  # install packages not available via conda
  - pip install coveralls
  - pip install geographiclib
  # current pyimgur stable release has a py2.6 incompatibility
  - pip install https://github.com/megies/PyImgur/archive/py26.zip
  - pip freeze
  - conda list
  # done installing dependencies
  - git version
  - pip install .
script:
  # Run the tests available, more should be added
  - python eqcorrscan/tests/runtests.py

notifications:
    email: false
