
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a13'
version_full = 'b03eb647e0ac3e7a37f1cd25fb8ea90524d42e1d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

