
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9b1d1b669030ea9b6ef22eee767dc5ddc64e4550",
 "version": "1.2.0-0-g9b1d1b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
