language: python

# Run travis, run
# Run converalls, run
# Use container-based infrastructure
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install coveralls
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
