language: python
os:
- linux
python:
#- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- 'nightly'
cache:
  apt: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq
- pip install --upgrade setuptools
- pip install --upgrade pip
install:
- pip install .
script:
# test - cd tests && bats ${CI:+--tap} ./tests_run.sh
