
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "519560e9a38ac4a17da307b7f207c8a0fc426992",
 "version": "v0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
