# This file was auto-generated by zetup
#
# https://bitbucket.org/userzimmermann/zetup.py


from __future__ import absolute_import

import sys
import os
from collections import OrderedDict

from zetup.version import Version
from zetup.dist import Distribution
from zetup.requires import Requirements
from zetup.extras import Extras
from zetup.package import Packages, Package
from zetup.notebook import Notebook



zfg = sys.modules[__name__]

NAME = 'modeled.netconf'

CLASSIFIERS = ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)', 'Operating System :: OS Independent', 'Topic :: Software Development', 'Topic :: Utilities', 'Programming Language :: Python', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4']

URL = 'https://bitbucket.org/userzimmermann/python-modeled.netconf'

EMAIL = 'zimmermann.code@gmail.com'

SETUP_KEYWORDS = None

DESCRIPTION = 'Highly Pythonized NETCONF and YANG'

SETUP_HOOKS = []

TITLE = 'modeled.netconf'

VERSION = Version('0.0.1')

FORCE_MAKE = True

PYTHON = ['2.7', '3.3', '3.4']

SETUP_REQUIRES = None

AUTHOR = 'Stefan Zimmermann'

REQUIRES = Requirements("""
zetup >= 0.2.27
backports.socketpair >= 3.5.0
moretools >= 0.1.7
modeled >= 0.1.8
netconf >= 0.3.1
pyang >= 1.6

""", zfg=zfg)

KEEP_MADE = ['setup.py', 'tox.ini']

NO_MAKE = ['tox.ini']

PACKAGES = Packages([

Package('modeled.netconf',
  sources=[
    '__init__.py'
    ],
  subpackages=[
    
Package('modeled.netconf.yang',
  sources=[
    'common.py',
    'container.py',
    'module.py',
    'rpc.py',
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )

    ],
  )

  ], root=os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))

SCRIPTS = None

DISTRIBUTION = Distribution(zfg)

LICENSE = 'LGPLv3'

KEYWORDS = ['netconf', 'yang', 'yin', 'server', 'client', 'ssh', 'rpc', 'xml', 'xmlrpc', 'modeled', 'model', 'modeling', 'modelled', 'modelling', 'serialization', 'exchange', 'mapping', 'pyang', 'paramiko', 'python3']

EXTRAS = Extras([

], zfg=zfg)

MODULES = []

TEST_COMMANDS = ['py.test -v test']