sudo: required
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install -y postgresql-9.3
  - sudo apt-get install -y postgresql-contrib-9.3 postgresql-plpython-9.3
  - psql -c 'create database newslynx;' -U postgres

sudo: yes

addons:
  postgresql: "9.3"

services:
  - redis-server

script:
    - mkdir ~/.newslynx/
    - wget https://raw.githubusercontent.com/newslynx/newslynx-core/master/newslynx/app/config.yaml -O ~/.newslynx/config.yaml
    - make app_install