__version__ = "0.3.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.3.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f2c209c65e4ba42eb362ce7e46c7d727ecbf75aa'
__git_head_subject__ = 'Finished release v0.3.7.'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2015-11-08 11:56:55'
