
/* #########################################################################
 * [2015-11-11 11:24:05.911000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___BASE_NODE_RPC___
#define ___BASE_NODE_RPC___

#include "BaseNodeRpc/Properties.h"
#include "BaseNodeRpc/CommandProcessor.h"

#endif  // #ifndef ___BASE_NODE_RPC___

