language: python
python: 2.7
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
env:
  - TARGET=test
  - TARGET=coverage.sh
  - TARGET=code-analysis

install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg --setuptools-version=18.3.2 --buildout-version=2.4.4
  - bin/buildout -c travis.cfg -q -t 7 

script: bin/$TARGET
