
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5f044e23d6a1deeb3a1339441b016e02b6b373ce",
 "version": "0.2.post30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
