language: python
sudo: false
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
env:
   - DJANGO_VERSION=1.7
   - DJANGO_VERSION=1.8
matrix:
   # Django 1.7 doesn't support python 3.5
   exclude:
      - python: "3.5"
        env: DJANGO_VERSION=1.7
# command to install dependencies,
install:
   # Install the right version of Django first
   - pip install 'Django<='"$DJANGO_VERSION"
   - pip install -r requirements.txt -r requirements-dev.txt
# command to run tests
script: NOSE_WITH_COVERAGE=1 python manage.py test
