#!/usr/bin/env python

class ArrowHeadProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Length': 'LineArrowheadLength',
            'Style': 'LineArrowheadStyle',
            'Width': 'LineArrowheadWidth'

        }

        self.attributeMap = {
            'Length': 'Length','Style': 'Style','Width': 'Width'}       

        self.Length = None # LineArrowheadLength
        self.Style = None # LineArrowheadStyle
        self.Width = None # LineArrowheadWidth
        
