#!/usr/bin/env python

class HtmlExportOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'SaveAsZip': 'bool',
            'SubDirectoryName': 'str',
            'ExportFormat': 'ExportFormats'

        }

        self.attributeMap = {
            'SaveAsZip': 'SaveAsZip','SubDirectoryName': 'SubDirectoryName','ExportFormat': 'ExportFormat'}       

        self.SaveAsZip = None # bool
        self.SubDirectoryName = None # str
        self.ExportFormat = None # ExportFormats
        
