#!/usr/bin/env python

class Image(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Width': 'int',
            'Height': 'int',
            'SelfUri': 'ResourceUri',
            'AlternateLinks': 'list[ResourceUri]',
            'Links': 'list[ResourceUri]'

        }

        self.attributeMap = {
            'Width': 'Width','Height': 'Height','SelfUri': 'SelfUri','AlternateLinks': 'AlternateLinks','Links': 'Links'}       

        self.Width = None # int
        self.Height = None # int
        self.SelfUri = None # ResourceUri
        self.AlternateLinks = None # list[ResourceUri]
        self.Links = None # list[ResourceUri]
        
