#!/usr/bin/env python

class Placeholder(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Index': 'int',
            'Orientation': 'PlaceholderOrientation',
            'Size': 'PlaceholderSize',
            'Type': 'PlaceholderType',
            'Shape': 'ResourceUriElement',
            'SelfUri': 'ResourceUri',
            'AlternateLinks': 'list[ResourceUri]',
            'Links': 'list[ResourceUri]'

        }

        self.attributeMap = {
            'Index': 'Index','Orientation': 'Orientation','Size': 'Size','Type': 'Type','Shape': 'Shape','SelfUri': 'SelfUri','AlternateLinks': 'AlternateLinks','Links': 'Links'}       

        self.Index = None # int
        self.Orientation = None # PlaceholderOrientation
        self.Size = None # PlaceholderSize
        self.Type = None # PlaceholderType
        self.Shape = None # ResourceUriElement
        self.SelfUri = None # ResourceUri
        self.AlternateLinks = None # list[ResourceUri]
        self.Links = None # list[ResourceUri]
        
