#!/usr/bin/env python

class Slide(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Width': 'float',
            'Height': 'float',
            'Shapes': 'ResourceUriElement',
            'Theme': 'ResourceUriElement',
            'Placeholders': 'ResourceUriElement',
            'Images': 'ResourceUriElement',
            'Comments': 'ResourceUriElement',
            'Background': 'ResourceUriElement',
            'SelfUri': 'ResourceUri',
            'AlternateLinks': 'list[ResourceUri]',
            'Links': 'list[ResourceUri]'

        }

        self.attributeMap = {
            'Width': 'Width','Height': 'Height','Shapes': 'Shapes','Theme': 'Theme','Placeholders': 'Placeholders','Images': 'Images','Comments': 'Comments','Background': 'Background','SelfUri': 'SelfUri','AlternateLinks': 'AlternateLinks','Links': 'Links'}       

        self.Width = None # float
        self.Height = None # float
        self.Shapes = None # ResourceUriElement
        self.Theme = None # ResourceUriElement
        self.Placeholders = None # ResourceUriElement
        self.Images = None # ResourceUriElement
        self.Comments = None # ResourceUriElement
        self.Background = None # ResourceUriElement
        self.SelfUri = None # ResourceUri
        self.AlternateLinks = None # list[ResourceUri]
        self.Links = None # list[ResourceUri]
        
