#!/usr/bin/env python

class SlideBackground(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Type': 'str',
            'FillFormat': 'FillFormat',
            'SelfUri': 'ResourceUri',
            'AlternateLinks': 'list[ResourceUri]',
            'Links': 'list[ResourceUri]'

        }

        self.attributeMap = {
            'Type': 'Type','FillFormat': 'FillFormat','SelfUri': 'SelfUri','AlternateLinks': 'AlternateLinks','Links': 'Links'}       

        self.Type = None # FillType
        self.FillFormat = None # FillFormat
        self.SelfUri = None # ResourceUri
        self.AlternateLinks = None # list[ResourceUri]
        self.Links = None # list[ResourceUri]
        
