
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '3.2.5rc2'
version_full = '71d5fed29f25c9fd33d3accb80048e5f6bfb5e91'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

