
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b2bf3849de74593aa025f70be051783e1acb7a9f",
 "version": "0.2.post12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
