
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6454b0c869d48093557803bcb6792e806ce98513",
 "version": "1.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
