
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "19ae0ad604f3e6e9ca505e3b06b7a520e56fa58e",
 "version": "0.1.0a24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
