
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cf600f7c81babb1943bf469886d97ccecc077749",
 "version": "2.7.post.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
