from rambutan3.check_args.binary_seq.RBinarySequenceEnum import RBinarySequenceEnum
from rambutan3.check_args.binary_seq.RBinarySequenceMatcher import RBinarySequenceMatcher


BYTES = RBinarySequenceMatcher(RBinarySequenceEnum.BYTES)
