language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: pypy3
    - python: 3.3
    - python: 3.4
before_install:
  - git config --global user.name "Temp user"
  - git config --global user.email "temp@example.com"
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - python bootstrap.py
  - bin/buildout
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coverage==3.7 coveralls
  - coveralls
