
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a2'
version_full = '78c295a4e93976bdf6f306bf082ba1f3bfb15c66'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

