# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epsilon/data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='epsilon/data.proto',
  package='',
  syntax='proto3',
  serialized_pb=b'\n\x12\x65psilon/data.proto\",\n\x06Vector\x12\r\n\x05value\x18\x01 \x03(\x01\x12\x13\n\x0bvalue_bytes\x18\x02 \x01(\x0c\"H\n\x0cSparseMatrix\x12\t\n\x01m\x18\x01 \x01(\x05\x12\t\n\x01n\x18\x02 \x01(\x05\x12\n\n\x02pr\x18\x03 \x03(\x01\x12\n\n\x02jc\x18\x04 \x03(\x03\x12\n\n\x02ir\x18\x05 \x03(\x03\"G\n\x0b\x44\x65nseMatrix\x12\t\n\x01m\x18\x01 \x01(\x05\x12\t\n\x01n\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x03(\x01\x12\x13\n\x0bvalue_bytes\x18\x04 \x01(\x0c\"\xab\x01\n\x04\x44\x61ta\x12\x1d\n\tdata_type\x18\x01 \x01(\x0e\x32\n.Data.Type\x12\"\n\x0c\x64\x65nse_matrix\x18\x02 \x01(\x0b\x32\x0c.DenseMatrix\x12$\n\rsparse_matrix\x18\x03 \x01(\x0b\x32\r.SparseMatrix\x12\r\n\x05value\x18\x05 \x01(\x0c\"+\n\x04Type\x12\x10\n\x0c\x44\x45NSE_MATRIX\x10\x00\x12\x11\n\rSPARSE_MATRIX\x10\x01\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DATA_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Data.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DENSE_MATRIX', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPARSE_MATRIX', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_DATA_TYPE)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Vector.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_bytes', full_name='Vector.value_bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=66,
)


_SPARSEMATRIX = _descriptor.Descriptor(
  name='SparseMatrix',
  full_name='SparseMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='SparseMatrix.m', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n', full_name='SparseMatrix.n', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pr', full_name='SparseMatrix.pr', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jc', full_name='SparseMatrix.jc', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ir', full_name='SparseMatrix.ir', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=140,
)


_DENSEMATRIX = _descriptor.Descriptor(
  name='DenseMatrix',
  full_name='DenseMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='DenseMatrix.m', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n', full_name='DenseMatrix.n', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DenseMatrix.value', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_bytes', full_name='DenseMatrix.value_bytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=213,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='Data.data_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_matrix', full_name='Data.dense_matrix', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparse_matrix', full_name='Data.sparse_matrix', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Data.value', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATA_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=387,
)

_DATA.fields_by_name['data_type'].enum_type = _DATA_TYPE
_DATA.fields_by_name['dense_matrix'].message_type = _DENSEMATRIX
_DATA.fields_by_name['sparse_matrix'].message_type = _SPARSEMATRIX
_DATA_TYPE.containing_type = _DATA
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['SparseMatrix'] = _SPARSEMATRIX
DESCRIPTOR.message_types_by_name['DenseMatrix'] = _DENSEMATRIX
DESCRIPTOR.message_types_by_name['Data'] = _DATA

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'epsilon.data_pb2'
  # @@protoc_insertion_point(class_scope:Vector)
  ))
_sym_db.RegisterMessage(Vector)

SparseMatrix = _reflection.GeneratedProtocolMessageType('SparseMatrix', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEMATRIX,
  __module__ = 'epsilon.data_pb2'
  # @@protoc_insertion_point(class_scope:SparseMatrix)
  ))
_sym_db.RegisterMessage(SparseMatrix)

DenseMatrix = _reflection.GeneratedProtocolMessageType('DenseMatrix', (_message.Message,), dict(
  DESCRIPTOR = _DENSEMATRIX,
  __module__ = 'epsilon.data_pb2'
  # @@protoc_insertion_point(class_scope:DenseMatrix)
  ))
_sym_db.RegisterMessage(DenseMatrix)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'epsilon.data_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  ))
_sym_db.RegisterMessage(Data)


# @@protoc_insertion_point(module_scope)
