
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.10.2'
version_full = '755ae11a7e197b4d6c49506c3790d2b45645d99b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

