
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9eba3253855c18153e25ac058dfb596c933e60c5",
 "version": "0.1.0a27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
