"""
   CorasLib.Models.AllocationSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper
from CorasLib.Models.AllocationItemSerializer import AllocationItemSerializer

class AllocationSerializer(object):

    """Implementation of the 'AllocationSerializer' model.

    TODO: type model description here.

    Attributes:
        url (string): TODO: type description here.
        items (list of AllocationItemSerializer): TODO: type description
            here.
        state (int): TODO: type description here.
        recipient (string): TODO: type description here.
        id (string): TODO: type description here.
        item_types (int): TODO: type description here.
        event (string): TODO: type description here.
        count (int): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the AllocationSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    url -- string -- Sets the attribute url
                    items -- list of AllocationItemSerializer -- Sets the attribute items
                    state -- int -- Sets the attribute state
                    recipient -- string -- Sets the attribute recipient
                    id -- string -- Sets the attribute id
                    item_types -- int -- Sets the attribute item_types
                    event -- string -- Sets the attribute event
                    count -- int -- Sets the attribute count
        
        """
        # Set all of the parameters to their default values
        self.url = None
        self.items = None
        self.state = None
        self.recipient = None
        self.id = None
        self.item_types = None
        self.event = None
        self.count = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "url": "url",
            "items": "items",
            "state": "state",
            "recipient": "recipient",
            "id": "id",
            "item_types": "item_types",
            "event": "event",
            "count": "count",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "items" in kwargs:
                # Parameter is an array, so we need to iterate through it
                self.items = list()
                for item in kwargs["items"]:
                    self.items.append(AllocationItemSerializer(**item))

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "url": "url",
            "items": "items",
            "state": "state",
            "recipient": "recipient",
            "id": "id",
            "item_types": "item_types",
            "event": "event",
            "count": "count",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)