"""
   CorasLib.Models.WriteEventSerializer
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""
from CorasLib.APIHelper import APIHelper

class WriteEventSerializer(object):

    """Implementation of the 'WriteEventSerializer' model.

    TODO: type model description here.

    Attributes:
        announce (DateTime): TODO: type description here.
        configuration (string): TODO: type description here.
        venue (string): TODO: type description here.
        general_onsale (DateTime): TODO: type description here.
        restriction (string): TODO: type description here.
        name (string): TODO: type description here.
        doors (DateTime): TODO: type description here.
        end (DateTime): TODO: type description here.
        start (DateTime): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the WriteEventSerializer class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    announce -- DateTime -- Sets the attribute announce
                    configuration -- string -- Sets the attribute configuration
                    venue -- string -- Sets the attribute venue
                    general_onsale -- DateTime -- Sets the attribute general_onsale
                    restriction -- string -- Sets the attribute restriction
                    name -- string -- Sets the attribute name
                    doors -- DateTime -- Sets the attribute doors
                    end -- DateTime -- Sets the attribute end
                    start -- DateTime -- Sets the attribute start
        
        """
        # Set all of the parameters to their default values
        self.announce = None
        self.configuration = None
        self.venue = None
        self.general_onsale = None
        self.restriction = None
        self.name = None
        self.doors = None
        self.end = None
        self.start = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "announce": "announce",
            "configuration": "configuration",
            "venue": "venue",
            "general_onsale": "general_onsale",
            "restriction": "restriction",
            "name": "name",
            "doors": "doors",
            "end": "end",
            "start": "start",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "announce": "announce",
            "configuration": "configuration",
            "venue": "venue",
            "general_onsale": "general_onsale",
            "restriction": "restriction",
            "name": "name",
            "doors": "doors",
            "end": "end",
            "start": "start",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)