
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a42b592904914cce626298f9a7fbd84f5e336365",
 "version": "0.3.post13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
