__version__ = "0.3.10"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(HEAD detached at v0.3.10)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'a6aed05cfd56361a1e2aa5ecae41df9c9ddf140a'
__git_head_subject__ = 'HPT-1681'
__git_head_message__ = ''
__git_dirty_diff__ = ''