
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "443279efa833689e14607d6ff01d58a3d0ddd990",
 "version": "0.1.0a25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
