
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "09e63449a4f2caa3834cc2f7d92a357571e12517",
 "version": "0.1.0a32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
