__version__ = "0.4.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.4.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cdface548b89ed6967783c410902d2a0e0027315'
__git_head_subject__ = 'Finished release v0.4.7.'
__git_head_message__ = ''
__git_dirty_diff__ = ''