language: python
python:
- '2.7'
- '3.4'
- '3.5'
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- conda create -n testenv --yes --file requirements-conda.txt python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install --yes pytest
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- pip install coveralls
- echo $PATH
- which python
- which pip
- which py.test
- python --version
- conda info
- conda list
install:
- python setup.py install
script:
- py.test
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then coveralls; fi
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
- provider: pypi
  user: andsor
  password:
    secure: VbGhiW+x1y+NF2kctOqfZKM2zHgUR1qCFbkhrP++7XVq4AU1aZHDqVze4r0pHsEerMZjWRFjThG0SBTvxog+87xsjVwIwUF6x+P3BmYhukOW/KMz9hdeaqM88cVyEEAnJooUSBljKGp21wZxeVmkc5H1vcUzGsqKwYEIUKInfLKHv+phwsa7H57aOVJlBrXW8cevx8rYccZ9T6DPSh/pDNSW/pdmL8M6t0DWJUF/GKKYhfQevIcsnHuRf45Valuzykk82P8ewL98RQtEH8Motb5iJOd8XV5/t0pQpAA+XyZKx0QCXVNll5xkpAVJ13fgg87Dg5PlHhD47d6xVBLHUyuAc2Wbe2atldBammYqiUo3KLcPG4M8s679uSmG7d239P55Pn4pY2wAIsepug4NvPIgqDQ1dUh9dp0IfloWLTq75K6GaEqZHdGu8T3QBbA0jfjOaBjHuGHqdbKGWLMNaKdLKgZfm7fUDl+jYs8MzELq45I9YlhNmnmGqY2urLg9HgLU+7BGk6TiDBO7v5Mm34r1GWK8TV3QWvg5eB2GuVCLiJnsvgXbxxUqctYHpPdSmfAkYVV49ECN8q7zP/BCRfAeSNZlBN88RaEKpddlZ8TflSZ7FGGgtDGBk8i72T3R3sWT24T8kSFm5agAoJSsMcRZReXwWA4x9Vgf93j8/iU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: andsor/pyfssa
    python: 3.5
    branch: master
- provider: releases
  api_key:
    secure: Jw3guxpOcjECxvGkE7xtRglPVQT8p8cTBvZdBykU2eAOaL3uI38IFO2sDevy3DWG4tCJrgymPhxvWL2Jffc4xCsI+3ZPDkYHMbP/g01lvGSA2PFcc7u2s+G8l+FTmUT8uCN4cAF6ks/jRxWuBCG+bE4TXGAF2WPct5PV/BJASuTcj1BZdPC7jJ+IQSIJQN3BEz1HZI/1R0lWs46kuqLt1588yXxOItzOqoQ2yMOclYlcYwLSFvapnkhjBfyRDz38GFuDEzecTc4nFQk+zto7gdyV/wiAQQgeqVmwU27L5aMV6Qt1xJL/kFU4mPoG9fKzhkL4PYXyKhvvkxBJHgj97okRlSvxB1ebtgPnvKvRtNmEbZmANhioQC+qSVkk4K5OpuwYoWNxZjG3G60zAi5IceTuT09lQigFz4zamd2U8bFMKsMCSI2OAMjYP8hJEKKwNB32QTiXgcb9RDhauZu+zZXVv7rqBEg9ABg0QbLZ7X4fztOYNY3fio0rTsSqDpzWHHZTsX0fa4U2svKGBIxr/xdYAhYoSQ/SmHbgREk3yH92ffjH1FD/H9U9S01vtF+R9l0jKtBqqaZW2rnvZOLM652mk8O1S7dpyUfFC4H6Sk4wX13+EGE1Ajdo/uOkNfLSqzmWyolG9InjYRH6aBnFq6GeQIIDOap0CdIauCZxVaE=
  on:
    tags: true
    python: 3.5
    branch: master
