site_name: supernova
pages:
  - 'Home': 'index.md'
  - 'Getting started': 'gettingstarted.md'
  - 'Rackspace quick start': 'raxquickstart.md'
  - 'Installing supernova': 'installation.md'
  - 'Configuration': 'configuring.md'
  - 'Usage': 'usingsupernova.md'
  - 'Troubleshooting': 'troubleshooting.md'
theme: readthedocs
repo_url: https://github.com/major/supernova
