
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f220aab2d3c763bc8efdc6a360d258b5046b4a18",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
