language: python
python: 2.7
sudo: true
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - DOCKER_STORAGE_DRIVER=devicemapper
    - PYKONG_TEST_API_URL=http://localhost:8001
  matrix:
    - TOXENV=check
    - TOXENV=2.6,coveralls
    - TOXENV=2.6-nocover
    - TOXENV=2.7,coveralls
    - TOXENV=2.7-nocover
    - TOXENV=3.3,coveralls
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls
    - TOXENV=3.4-nocover
    - TOXENV=pypy,coveralls
    - TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  - pip install tox
script:
  - ./run 'scripts/docker/cassandra.sh; sleep 5'
  - ./run 'scripts/docker/kong.sh; sleep 5'
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
