language: python
python:
    - "2.7"
#   - "3.3"
#   - "3.4"
#   - "pypy"
env:

before_script:

install:
    - pip install -q -r requirements.txt
    - pip install .

script:
    # fixme:
    - python unit-test/Spice/test_BasicElement.py

####################################################################################################
#
# End
#
####################################################################################################
