
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2bfe658535a08208c2dd411c12490cfdf18bfe",
 "version": "0.1.0a31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
