
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0ff2d712f840dbb718857b1cdf95460bd906b24d",
 "version": "0.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
