
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "50a4b104443dac24c33004bb5d0504c111854dbb",
 "version": "0.1.post19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
