__version__ = "0.1.15"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.1.15)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '056ffd2ff9070e613c29bad4f5c33a6f749986f4'
__git_head_subject__ = 'Finished release v0.1.15.'
__git_head_message__ = ''
__git_dirty_diff__ = ''