
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.3'
version_full = 'a0d48b49f43d4e7207a03a249a8537c1af9eae33'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

