
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "032c749616a56e8b9552439c3ce1282a940092f7",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
