
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b6188b49b202fe9c168d0434f12f34f3832f0150",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
