
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7c52da461b0ef441016dc45b2f3b15aef3edabd0",
 "version": "0.1.0a35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
