
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.5'
version_full = 'ba4474fefa45a65f6347cfa0949952c99e819272'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
