
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.0a4'
version_full = 'b7c94a2024828d9b28b96040c606b5407e69ff40'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

