
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d1526c4c3386c5b68146a69eae218f12cac1f35f",
 "version": "0.2.post10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
