# This file was auto-generated by salt's setup on Tuesday, 13 October 2015 @ 21:10:41 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 6, 0, 0, 0, None)
