
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7a5e9a51426b94de59f64e78c18fc647c2881cf2",
 "version": "2.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
