title: Parchment
subtitle: a simple static site generator
author: Taff Gao
social:
  twitter: https://twitter.com/gaotongfei
  github: https://github.com/gaotongfei
  #instagram:
  #weibo:
  #facebook:

contact: gaotongfei1995@gmail.com
avatar: 'img/avatar.png'
source: https://github.com/gaotongfei/parchment

theme: pure
