#   _   _   _   _   _   _   _   _
#  / \ / \ / \ / \ / \ / \ / \ / \
# ( n | e | w | s | l | y | n | x )
#  \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Secret Stuff

secret_key: changeme
app_secret_key: changemetoo
super_user: admin
super_user_email: changeme@example.com
super_user_password: admin
super_user_apikey: mj
super_user_org: 'admin'
super_user_timezone: UTC

# The Database URI (This is mandatory!)
sqlalchemy_database_uri: 'postgresql://localhost:5432/newslynx'

# API information for the app to know
api_url: http://localhost:5000 # Omit trailing slash.
api_version: v1
https: false # Change to `true` for production.

# needed for authentication with Facebook and Google Analytics
api_dns: http://<domain-name>:5000

# Directory which contains Sous Chefs
sous_chefs_dir: '~/.newslynx/sous-chefs/'

# Filepaths to default recipes + tags + reports to add for each
# new organization.
default_recipes: '~/.newslynx/defaults/recipes.yaml'
default_tags: '~/.newslynx/defaults/tags.yaml'

