"""
   CorasLib.Configuration

   This file was automatically generated by APIMATIC BETA v2.0 on 10/21/2015
"""

class Configuration :
    # The base Uri for API calls
    BASE_URI = "https://demo.coras.io"


