# Autogenerated by Astropy's setup.py on 2015-10-15 18:05:19.731933
from __future__ import unicode_literals
import datetime

version = "1.1b1"
githash = "af9bd871c3c610045ac9382ab4148e8ff9d88bcc"


major = 1
minor = 1
bugfix = 0

release = True
timestamp = datetime.datetime(2015, 10, 15, 18, 5, 19, 731933)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
