"""Initial setup

Revision ID: 3a94451d9c60
Revises: 
Create Date: 2015-09-18 21:01:51.086450

"""

# revision identifiers, used by Alembic.
revision = '3a94451d9c60'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('extras', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('root', sa.Text(), nullable=False),
    sa.Column('license_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('ssl', sa.Integer(), server_default=sa.text(u'0'), nullable=True),
    sa.Column('ssl_key', sa.Text(), nullable=True),
    sa.Column('ssl_certificate', sa.Text(), nullable=True),
    sa.Column('spdy', sa.Integer(), server_default=sa.text(u'0'), nullable=True),
    sa.Column('gzip', sa.Integer(), server_default=sa.text(u'1'), nullable=True),
    sa.Column('enabled', sa.Integer(), server_default=sa.text(u'0'), nullable=True),
    sa.Column('in_dev', sa.Integer(), server_default=sa.text(u'0'), nullable=True,),
    sa.Column('db_host', sa.Text(), nullable=True),
    sa.Column('db_name', sa.Text(), nullable=True),
    sa.Column('db_user', sa.Text(), nullable=True),
    sa.Column('db_pass', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('domains')
    ### end Alembic commands ###
