
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "82f7ecbd943583c8d6b41e5272369b0d19f4b0a9",
 "version": "0.1.0a30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
