
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f23c3afdd328fffd4bf048cf0e59dc7360d09c16",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
