
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.5'
version_full = '41db4bfbfd64ebf9483ee776dc90dc7b50f31e1f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

