
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3ac34e42f75aa263afd581ae08e6ded0e0958a28",
 "version": "0.3.post21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
