
/* #########################################################################
 * [2015-12-15 12:43:19.269000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___DROPBOT_DX___
#define ___DROPBOT_DX___

#include "DropbotDx/Properties.h"
#include "DropbotDx/CommandProcessor.h"

#endif  // #ifndef ___DROPBOT_DX___

