# This file was auto-generated by salt's setup on Tuesday, 01 December 2015 @ 21:12:02 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 3, 0, 0, 0, None)
