
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3'
version_full = '489b3ce5d0e6a9a7301ba5d345ba82fa824c1431'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

