sudo: false
language: python

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
  - ${HOME}/.cache
script:
  - pip install tox
  - tox -e flake8
  - tox -e py"${TRAVIS_PYTHON_VERSION/./}"
notifications:
  email: false

