
# This file was generated by 'versioneer.py' (0.11) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.5'
version_full = '4f77b51075fba8429f1785cf2010bcbe2c2f7058'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

