
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1'
version_full = '9d6fe86fd6442605ad9f01004d34d372c20834dd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

