# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.fields
import django_enumfield.tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', django.db.models.fields.IntegerField(default=0, enum=django_enumfield.tests.models.BeerStyle)),
                ('state', django.db.models.fields.IntegerField(blank=True, default=0, enum=django_enumfield.tests.models.BeerState, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django.db.models.fields.IntegerField(default=0, enum=django_enumfield.tests.models.LampState)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django.db.models.fields.IntegerField(default=1, enum=django_enumfield.tests.models.PersonStatus)),
            ],
        ),
    ]
