
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3e5b9957ec1849ebb7cd932dba5768403219b490",
 "version": "0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
