
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cefd15d0a1d22f7e1a285881827fc7093d914f7b",
 "version": "0.post.dev61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
